mesh_transformer/transformer_shard.py, resharding_example.py
It's likely this will work on a gpu with 16gb vram with a smaller "seq" size.
Without this change, the model immediately runs out of memory on "network = CausalTransformer(params)"
=> Implement early_cast option to support resharding on GPUs with less than 20gb vram

README.md
=> Correct 'Web demo' URL

mesh_transformer/transformer_shard.py, resharding_example.py
Without this, the model is actually duplicated in memory due to xmap.
I am testing with a single RTX 3090 on Ubuntu 20.04.2 LTS.
jax versions:
```
jax==0.2.13
jaxlib==0.1.67+cuda111
```
I also run with the following environment variables, otherwise it OOMs during init regardless of this change:
```
XLA_PYTHON_CLIENT_PREALLOCATE=false
XLA_PYTHON_CLIENT_ALLOCATOR=platform
```
Some stats on running infer() with and without this change:
before:
```
seq     vram usage
512     21.1G
900     22.3G
```
after:
```
seq     vram usage
512     14.7G
900     15.3G
2048    22.4G
```
It still uses a bit more than that during initialization though.
=> Significantly reduce vram usage when resharding on a single GPU.

mesh_transformer/sampling.py, mesh_transformer/transformer_shard.py, resharding_example.py
This seems to work quite well in combination with top_p, I posted some comparisons on discord.
Using "hk.with_rng" to keep the seed consistent across runs makes it much easier to compare changes in the sampling methods, I used this to compare with and without top_k:
Prompt
```
In a shocking finding, scientists discovered a herd of unicorns living in a remote, previously unexplored valley, in the Andes Mountains. Even more surprising to the researchers was the fact that the unicorns spoke perfect English. 
```
top_p=0.9, seed=0
```
They came from a forgotten time period, pre-dating even the Jurassic period, and carried themselves as if they belonged in the upper echelons of society. The scientists, Pym Verbrugge and Daisy Kowalewski of Edinburgh University, decided to name the new breed …
```
=> Implement top_k sampling

colab_demo.ipynb
I've had to run the notebook twice every time it's from a fresh notebook. (Because it always requires me to kernel restart after the first wget/update/etc.) This results in double-downloading the .zstd file. (The new one becomes a .1 file.) The -c parameter should allow wget to skip the second download if the file already exists. (Or it will finish downloading if it's not completely downloaded.)
=> wget -c for continue download if file exists

device_train.py, tfrecord_loader.py
Adds a script for training on the TPU VM, similar to the existing `device_sample.py`, etc.
My use case: I'm fine-tuning the model on a single TPU v3-8.  I initially got this working with the existing `train.py`, but
- I had to work around its expectations about file structure e.g. `meta.json`
- this way has lots of complexity that is needless here: using `ray`, using an extra VM outside the TPU, the `TPUCluster` wrapper, etc.
Note: I slapped this together hastily and it's not perfect.  I haven't yet verified it works on this branch, just on a personal dev branch with other changes.
**Step**
- Compared to `train.py`, I changed when `step` is incremented, to try to make the values in the checkpoint file names match the exact number of gradient steps that have been run.
- I increment the …
=> Add train script that runs on the TPU VM

mesh_transformer/util.py, slim_model.py
Contains some additions I made to `slim_model.py` when I was using it with a finetuned model.
- `--f16`: converts to float16
- Why: Since many people are doing inference with float16 weights, it seems better to just go directly to float16, without the bfloat16 step
- `--ckpt-step`: passing e.g. `--ckpt-step 401` will load from `step_401/` even if it's not the most recent checkpoint
- Why: I wanted to convert the model with the lowest val loss, but usually there were 1 or more checkpoints after that step
=> slim_model: options for float16, checkpoint selection

README.md, device_train.py
Fixes an issue where `device_train.py` didn't use the lr schedule params in the config correctly.
There are several notions of global step in this repo:
1. numbers in checkpoint paths
2. step in `meta.json`
3. counts stored in optax transforms (one for each transform with step state)
**Currently:**
`device_train.py` resets 1 and 2 to zero, but kept the step values in 3.
The schedule continues from the loaded step, which generally means finetuning happens at `end_lr`.
**This PR:**
I reset the optax step value for the lr schedule to zero.  This will give the expected warmup/anneal behavior from the config.
There's also a global step in the `scale_by_adam` state, for bias correction.  I don't reset this, as we're loading the accumulators and they don't need bias correction
----
Also …
=> Fix lr schedule in fine-tuning + add documentation

device_train.py, mesh_transformer/checkpoint.py
Adds the `--fresh-opt` arg to `device_train.py`.  This ignores the Adam state in the base ckpt (if it exists) and uses a fresh Adam
From my experiments + discussion in Discord, it's not clear if this is helpful or harmful overall.  It seems harmful early on, helpful at 1K+ steps, may increase overfitting?
----
This code can't load slim checkpoints, because it adds `opt_state` to network state before load, and thus expects a flattened structure built from a dict with an `opt_state`
I'm open to suggestions for how to do this.  The problem is that we need to know what structure to expect in the ckpt, before loading it
EDIT: [see here](https://github.com/nostalgebraist/mesh-transformer-jax/compare/fresh-opt..fresh-opt-slim-load) for a hacky but working implementation that can load the slim …
=> Fine-tuning: option to reset optimizer state

docker/.env, docker/Dockerfile, docker/README.md, docker/compose-proxy.yaml, docker/docker-compose.yaml, docker/main.py, docker/nginx_proxyvm.conf, docker/ops.py, docker/payloads.py, docker/start.sh
This PR adds Dockerization instructions and files to help deploy GPT-J as an API in TPU VM. 
Certain things have not been tested:
- The base Dockerfile image compatibility (there's no JAX docker image)
- Replication outside of our own GCP account
- SSL Issuance with a DNS that is not CloudFlare
=> Add Dockerization for GPT-J

mesh_transformer/transformer_shard.py
Convert logits to probabilities for all classes at every generation step and return them as single tensor with shape (1, gen_length, 1, vocab) in the output of CausalTransformer.generate()
resolves #41
=> Return probabilities from CausalTransformer.generate()

create_finetune_tfrecords.py
I noticed a problem with the `create_finetune_tfrecords` script I added recently.  It didn't work in the intended way when given long text files already "packed" with <|endoftext|>.
The problem was very hard to fix in the existing implementation (lightly adapted from create_tfrecords.py), because different levels of processing (archive, file, document, token sequence) were not cleanly separated in the code.
I refactored the code to separate these levels more clearly:
- `prep_and_tokenize_generator`:  iterable of strings --> iterable of tokenized documents
- `file_to_tokenized_docs_generator`: one file --> iterable of tokenized documents
- `arrays_to_sequences`: iterable of tokenized documents --> list of equal-length token arrays
I've tested this with a short test dataset in various …
=> Fixes for the create_finetune_tfrecords script

device_train.py, mesh_transformer/build_model.py, mesh_transformer/transformer_shard.py, mesh_transformer/util.py
- Modifies `CasualTransformer.train` to return gradient norms at the microbatch and single-example level
- Uses these to compute the gradient noise scale estimate `B_simple`, from Appendix A.1 of [An Empirical Model of Large-Batch Training](https://arxiv.org/abs/1812.06162)
- Restores the psum line that was removed [here](https://github.com/kingoflolz/mesh-transformer-jax/commit/02850c46c6b9d957b2a9214c2c6c291269648792#diff-c0219720e7ca7d79c74422022047497e12677c195f846ecf29af21017f6d21dfL21) so V1 grad clipping works properly
(For the psum change, I tried to do something that would turn off the psum in V2, but there's probably a better way to do it.  What I need for this PR to work is just psumming in V1)
----
Computing `B_simple` involves
1. measuring two quantities `G_noise` and …
=> Measure grad norm and noise scale in finetuning + fix grad clip in V1 CausalTransformer

howto_finetune.md, requirements.txt, to_hf_weights.py
A script to convert fine-tuned sharded weights into pytorch huggingface weights.
It unshards the weights and saves them as `{n}.pt` files. And creates `m.pt` to store mappings of `{huggingface_layer_attribute_id: weight_file_name.pt}` that can be used to load weights into a huggingface model.
It works on slimmed and full weights (though slimmed is recommended).
It can be run on tpu, gpu, or cpu. It takes a lot of memory ~30gb on cpu, or 12gb of gpu memory, or an unknown amount of tpu memory. But I only manage to get it that low by working on the weights individually and loading them when needed. A lot more memory optimization is almost certainly possible. It work with no OOM errors on a v3-8 tpu.
I've included a bunch of comments to hopefully make it easy to modify, and a nice cli for …
=> Adding script to convert fine-tuned sharded weights into pytorch huggingface weights.

howto_finetune.md
In discord, I see a lot of people keeping the `val_batches` value from 6B_roto_256.json in their finetuning configs.  This probably won't do what they expect.
Updates the finetuning guide to explain how to set this number.
=> Clarify val_batches

colab_demo.ipynb, mesh_transformer/checkpoint.py
This pull request includes a new implementation of read_ckpt, named read_ckpt_lowmem, in checkpoint.py that uses less system RAM and more device RAM so that the Colab demo will work correctly on all current TPU Colab instances. The original implementation will crash TPU Colab instances that don't have at least 13-14 GiB of system RAM.
=> Lower memory consumption in Colab demo

requirements.txt, to_hf_weights.py
There was a bug in `to_hf_weights.py` when saving the config. 
```python
with open(output_path / "config.json", "w") as file:
```
This would only work if the output_path was a local file path since it was using python's built in `open` method. I've switched it to use the Pathy version.
I also added pathy to the requirements. It's build on top of smart_open so it's not adding a lot to the project.
And I tweaked the `to_hf_weights.py` cli to use dashes instead of underscores so that it matched the rest of the cli's in MTJ.
=> Fixing config saving bug in to_hf_weights.py + adding pathy to requirements

README.md
Evaluation numbers as reported here:
https://developer.nvidia.com/blog/using-deepspeed-and-megatron-to-train-megatron-turing-nlg-530b-the-worlds-largest-and-most-powerful-generative-language-model/
Weights, flops, lambada ppl unreleased.
LAMBADA Acc: | 76.6%
Winogrande | 73.0%
Hellaswag | 80.2%
PIQA | 82.0%
*‡ were added to conform to the footnotes.  (evaluation numbers reported by their respective authors, trained with the Pile, which contains possible test set contamination)
=> Add Megatron-Turing NLG 530B numbers

README.md
Paper reports: "For all MassiveText subsets, we filter out non-English documents, process data into a homogeneous text-only format, deduplicate documents, and filter out documents too similar to those in our test sets." Therefore it seems safe to assume no test-set contamination.
https://storage.googleapis.com/deepmind-media/research/language-research/Training%20Gopher.pdf
=> add Gopher 230B results

requirements.txt
Because `tqdm` is not that serious package on this repo, there should not be too strict version description.
=> fix tqdm version conflict
